ADDED PRISMA GENERATE

diff --git a/apps/api/Dockerfile b/apps/api/Dockerfile
--- a/apps/api/Dockerfile
+++ b/apps/api/Dockerfile
@@ -30,12 +30,8 @@ RUN cat prisma/schema.prisma || echo "No schema.prisma file"
 RUN ls -la node_modules/.bin/prisma || echo "Prisma CLI not installed!"
 RUN bun run prisma:generate
 
-# # Create non-root user (Alpine way)
-RUN addgroup -g 1000 bun && adduser -u 1000 -G bun -s /bin/sh -D bun
-RUN chown -R bun:bun /app
-
 # Try to see the actual error
-RUN bunx prisma generate || (echo "Prisma generate failed" && exit 1)
+# RUN bunx prisma generate || (echo "Prisma generate failed" && exit 1)
 
 RUN bun run build
 
@@ -58,6 +54,7 @@ RUN chmod +x ./server
 ENV PORT=3000
 
 # run the app
+
 USER bun
 EXPOSE 3000/tcp
 
